### PR TITLE
open github from score

### PR DESCRIPTION
**Pull request by lesnitsky**

### CODE REVIEW

**Comment by Shastel** [comment]
How to open profile in a new tab then?

**Comment by lesnitsky** [comment]
maybe worth opening profiles in new tab by default then?

**Comment by Shastel** [comment]
I'm doing approx 50/50, but we should gather more feedback from someone who probably opens a lot of profiles? 😃
cc @dzmitry-varabei

**Comment by apalchys** [comment]
i vote for opening external links (github.com) in a new tab by default.

**Comment by lesnitsky** [comment]
The problem is that this link leads to two different locations:

1) https://app.rs.school/profile?githubId=<githubId> <https://app.rs.school/profile?githubId=%3CgithubId%3E>
2) https://github.com/<githubId> <https://github.com/%3CgithubId%3E>

Github seems to be secondary locations, so the idea is to open it with click modifier (meta or ctrl)
These modifiers default to "open link in new tab" though, so proposal is

1 opens in new tab by default 
2 opens github profile in new tab with ctrl/meta

**Comment by Shastel** [comment]
@apalchys external for sure, but we talking about `/profile?githubId=` page

**Comment by apalchys** [comment]
sorry for confusion. did check the PR carefully.

**Comment by dzmitry-varabei** [comment]
@lesnitsky @Shastel @apalchys Hi folks!
My two cents. Since we have two columns in the score - "Github" and "Name", we can use "Github" to open the Github profile and "Name" to open the RSAPP profile. For me, this behavior is more clear then the usage of click modifier

**Comment by lesnitsky** [comment]
@dzmitry-varabei implemented as you suggested
@apalchys could you please review?

**Pull request merged**
