### PR TITLE
refactor(cross-check): delete "Amend comment" button

### PR DESCRIPTION
**Pull request by NikitaKorevo**
**🟢 Add `deploy` label if you want to deploy this Pull Request to staging environment**

#### 🧑‍⚖️ Pull Request Naming Convention

- Title should follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- Do not put issue id in title
- Do not put WIP in title. Use [Draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) functionality
- Consider to add `area:*` label(s)

* [x] I followed naming convention rules

---

#### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Performance optimization
- [x] Refactoring
- [ ] Test Case
- [ ] Documentation update
- [ ] Other

#### 🔗 Related issue link

https://github.com/rolling-scopes/rsschool-app/pull/1921#issuecomment-1374006910

#### 💡 Background and solution

Deleted "Amend comment" button

Before: 

before

After: 

after

#### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Database migration is added or not needed
- [x] Documentation is updated/provided or not needed
- [x] Changes are tested locally

### CODE REVIEW

**Review by apalchys — APPROVED** [review]

**Review by AlreadyBored — APPROVED** [review]

**Comment by valerydluski** [comment]
don't merge, need to discuss

**Comment by valerydluski** [comment]
image

**Comment by NikitaKorevo** [comment]
закрываю PR т. к. кнопка "Amend comment" все еще нужна

**Comment by valerydluski** [comment]
@NikitaKorevo спасибо

**Pull request closed without merging**
