### PR TITLE
feat: implement answers highlighting

### PR DESCRIPTION
**Pull request by andreikovna**
**🟢 Add `deploy` label if you want to deploy this Pull Request to staging environment**

#### 🧑‍⚖️ Pull Request Naming Convention

- Title should follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- Do not put issue id in title
- Do not put WIP in title. Use [Draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) functionality
- Consider to add `area:*` label(s)

* [x] I followed naming convention rules

---

#### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Test Case
- [ ] Documentation update
- [ ] Other

#### 🔗 Related issue link
https://github.com/rolling-scopes/rsschool-app/issues/1573

#### 💡 Background and solution

image

#### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Database migration is added or not needed
- [x] Documentation is updated/provided or not needed
- [x] Changes are tested locally

### CODE REVIEW

**Comment by andreikovna** [comment]
#1573

**Comment by andreikovna** [comment]
#1573 Auto-Test feature

**Comment by AlreadyBored** [comment]
Could you please explain what is the purpose of these changes? Perhaps, I don't catch something :)

**Comment by valerydluski** [comment]
@andreikovna 
Thank you very much for your help. But this feature is not needed now. 
thank you eng

**Pull request closed without merging**
